In [63]:
# Read in the consolidated data
import pandas as pd

RES_consolidated = pd.read_excel('/Users/MattJohnson/Library/CloudStorage/OneDrive-UniversityofCapeTown/Masters_thesis/Data checks/Consolidation/Finalized/RES_aff_ref_output_1940_2010_affs_out authors Finalized.xlsx', 'Final RES')
RES_consolidated['year'] = RES_consolidated['year'].astype('int')
RES_consolidated['Article_ID'] = RES_consolidated['Article_ID'].astype('int')
RES_consolidated = RES_consolidated.reset_index(drop = True)
print(RES_consolidated.shape)
print(RES_consolidated.columns.values)
print(RES_consolidated.head())

(2116, 35)
['Unnamed: 0' 'Journal_Name' 'Authors_count' 'Authors_list' 'Article_ID'
 'content_type' 'stable_url' 'Ref_type' 'ref_string' 'ref_string_clean1'
 'year' '0_author_affs' '0_author_affs_consolidated'
 '0_author_affs_consolidated_0' '0_author_affs_consolidated_1'
 '0_author_affs_consolidated_2' '0_author_affs_consolidated_3'
 '1_author_affs' '1_author_affs_consolidated'
 '1_author_affs_consolidated_0' '1_author_affs_consolidated_1'
 '2_author_affs' '2_author_affs_consolidated'
 '2_author_affs_consolidated_0' '2_author_affs_consolidated_1'
 '2_author_affs_consolidated_2' '3_author_affs'
 '3_author_affs_consolidated' '3_author_affs_consolidated_0'
 '3_author_affs_consolidated_1' '4_author_affs'
 '4_author_affs_consolidated' '4_author_affs_consolidated_0'
 '5_author_affs' '5_author_affs_consolidated']
   Unnamed: 0 Journal_Name  Authors_count          Authors_list  Article_ID  \
0           0          JPE              1       ['Oscar Lange']     2967419
1           1          JPE              1        ['M. Polanyi']     2967413
2           2          JPE              1         ['L. Rostas']     2967414
3           3          JPE              1     ['Marian Bowley']     2967415
4           4          JPE              1  ['G. L. S. Shackle']     2967416

  content_type                            stable_url Ref_type  \
0      Article  https://www.jstor.org/stable/2967419    found
1      Article  https://www.jstor.org/stable/2967413    found
2      Article  https://www.jstor.org/stable/2967414    found
3      Article  https://www.jstor.org/stable/2967415    found
4      Article  https://www.jstor.org/stable/2967416    found

                                          ref_string  \
0  COMPLEMENTARITY AND INTERRELATIONS OF SHIFTS 6...
1  ECONOMICS BY MOTION SYMBOLS I9\n\nfrom the rep...
2  CAPITAL LEVIES IN CENTRAL EUROPE, r91i9-1924 3...
3  LOCAL RATES AND HOUSING SUBSIDIES 43\nV\n\nSo ...
4  48 THE REVIEW OF ECONOMIC STUDIES\n\nSudden an...

                                   ref_string_clean1  ...  \
0  Complementarity And Interrelations Of Shifts 6...  ...
1  Economics By Motion Symbols I9\n\nFrom The Rep...  ...
2  Capital Levies In Central Europe, R91I9-1924 3...  ...
3  Local Rates And Housing Subsidies 43\nV\n\nSo ...  ...
4  48 The Review Of Economic Studies\n\nSudden An...  ...

   2_author_affs_consolidated_2 3_author_affs 3_author_affs_consolidated  \
0                           NaN           NaN                        NaN
1                           NaN           NaN                        NaN
2                           NaN           NaN                        NaN
3                           NaN           NaN                        NaN
4                           NaN           NaN                        NaN

  3_author_affs_consolidated_0 3_author_affs_consolidated_1 4_author_affs  \
0                          NaN                          NaN           NaN
1                          NaN                          NaN           NaN
2                          NaN                          NaN           NaN
3                          NaN                          NaN           NaN
4                          NaN                          NaN           NaN

  4_author_affs_consolidated 4_author_affs_consolidated_0 5_author_affs  \
0                        NaN                          NaN           NaN
1                        NaN                          NaN           NaN
2                        NaN                          NaN           NaN
3                        NaN                          NaN           NaN
4                        NaN                          NaN           NaN

  5_author_affs_consolidated
0                          x
1                        NaN
2                        NaN
3                        NaN
4                        NaN

[5 rows x 35 columns]

In [64]:
#Read in the master sheet
#Local store of AER_master
RES_master = pd.read_excel('/Users/MattJohnson/Desktop/Affiliations/1_Input files and processing input files/1_1_Input files/Master lists/Processed/RES_processed.xlsx')
for i in range(len(RES_master)):
    RES_master.loc[i,['Article_ID']] = RES_master.loc[i,['stable_url']].to_string().rsplit('/',1)[-1]

RES_master_condenced  = RES_master[['Article_ID','year','authors','content_type']]
RES_master_condenced['year'] = RES_master_condenced['year'].astype('int')
RES_master_condenced['Article_ID'] = RES_master_condenced['Article_ID'].astype('int')
RES_master_condenced.rename(columns = {'year':'year_master', 'content_type':'content_type_master'}, inplace = True)

list = []
for i in range(1940,2011):
    list.append(i)
print(list)
#mask_year = RES_master_condenced['year_master'].isin([2016,2015,2014,2013,2012,2011])
mask_year = RES_master_condenced['year_master'].isin(list)
RES_master_condenced = RES_master_condenced[mask_year]
#mask_type = RES_master_condenced['content_type_master'].isin(['Rejoiner','MISC','Review'])
#RES_master_condenced = RES_master_condenced[~mask_type]
mask_type = RES_master_condenced['content_type_master'].isin(['Article',])
RES_master_condenced = RES_master_condenced[mask_type]
#RES_master_condenced.drop(~RES_master_condenced.loc[RES_master_condenced['year_master'].isin([2016])].index, inplace=True)
print(RES_master_condenced.shape)
RES_master_condenced.head()

[1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010]
(2608, 4)

/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_88028/1764392342.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RES_master_condenced['year'] = RES_master_condenced['year'].astype('int')
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_88028/1764392342.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RES_master_condenced['Article_ID'] = RES_master_condenced['Article_ID'].astype('int')
/var/folders/23/ft9qf9c11rj_vqhbjml910f40000gn/T/ipykernel_88028/1764392342.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RES_master_condenced.rename(columns = {'year':'year_master', 'content_type':'content_type_master'}, inplace = True)

,Article_ID,year_master,authors,content_type_master
493,40836646,2010,SULE ALAN and MARTIN BROWNING,Article
494,40836647,2010,SIWAN ANDERSON and DEBRAJ RAY,Article
495,40836648,2010,MANUEL F. BAGUES and BERTA ESTEVE-VOLART,Article
496,40836649,2010,"TIMOTHY BESLEY, TORSTEN PERSSON and DANIEL M. ...",Article
497,40836650,2010,"MARTIN BROWNING, METTE EJRNJES and JAVIER ALVAREZ",Article

In [65]:
# Merging the masterfile onto the new melted file to get additional data
consolidated_master_merged = RES_master_condenced.merge(RES_consolidated, how = 'left', on = 'Article_ID')
consolidated_master_merged = consolidated_master_merged.sort_values(by=['year_master'])
consolidated_master_merged = consolidated_master_merged.reset_index(drop = True)

In [66]:
# Excel output to get an overview of the data
consolidated_master_merged.head
consolidated_master_merged.to_excel('/Users/MattJohnson/Desktop/Affiliations/2_Extracting affilitations/3_consolidation/RES/Scopus/RES_master merge.xlsx')

In [67]:
#Original scopus
import pandas as pd

RES_scopus = pd.read_excel('/Users/MattJohnson/Desktop/Affiliations/1_Input files and processing input files/1_1_Input files/Scopus files/RES_scopus.xlsx')
for i in range(len(RES_scopus)):
    RES_scopus.loc[i,['Article_ID']] = RES_scopus.loc[i,['DOI']].to_string().rsplit('/',1)[-1]
#RES_scopus['Article_ID'] = RES_scopus['Article_ID'].astype('int')
RES_scopus  = RES_scopus[['Article_ID','authors','affiliations']]

print(RES_scopus.head())

  Article_ID       authors                 affiliations
0    2967407    Kaldor, N.       London, United Kingdom
1    2967407           NaN                          NaN
2  7.2.138-a           NaN                          NaN
3    2967408    Kaldor, N.       London, United Kingdom
4    7.2.137  Somers, H.M.  Berkeley, CA, United States

In [68]:
# Scopus consolidated
import pandas as pd

RES_scopus = pd.read_excel('/Users/MattJohnson/Library/CloudStorage/OneDrive-UniversityofCapeTown/Masters_thesis/Data checks/Consolidation/Finalized/RES_scopus to add.xlsx')
#for i in range(len(RES_scopus)):
#    RES_scopus.loc[i,['Article_ID']] = RES_scopus.loc[i,['DOI']].to_string().rsplit('/',1)[-1]
RES_scopus['Article_ID'] = RES_scopus['Article_ID'].astype('str')
RES_scopus  = RES_scopus[['Article_ID', 'Manual', '0_author_affs_consolidated_0','0_author_affs_consolidated_1','0_author_affs_consolidated_2',
                          '1_author_affs_consolidated_0','1_author_affs_consolidated_1',
                          '2_author_affs_consolidated_0','2_author_affs_consolidated_1',
                          '3_author_affs_consolidated_0']]

RES_scopus.rename(columns = {'0_author_affs_consolidated_0':'0_author_affs_consolidated_0_scopus', 
                             '0_author_affs_consolidated_1':'0_author_affs_consolidated_1_scopus',
                             '0_author_affs_consolidated_2':'0_author_affs_consolidated_2_scopus',
                             '1_author_affs_consolidated_0':'1_author_affs_consolidated_0_scopus',
                             '1_author_affs_consolidated_1':'1_author_affs_consolidated_1_scopus',
                             '2_author_affs_consolidated_0':'2_author_affs_consolidated_0_scopus',
                             '2_author_affs_consolidated_1':'2_author_affs_consolidated_1_scopus',
                             '3_author_affs_consolidated_0':'3_author_affs_consolidated_0_scopus'}, inplace = True)
print(RES_scopus.head())

  Article_ID  Manual 0_author_affs_consolidated_0_scopus  \
0    2967408  Scopus                                 NaN
1    2967408  Scopus        London United Kingdom (City)
2    2967640  Scopus     Washington United States (City)
3    2967492  Scopus        London United Kingdom (City)
4    2967520  Scopus     Stillwater United States (City)

  0_author_affs_consolidated_1_scopus 0_author_affs_consolidated_2_scopus  \
0                                 NaN                                 NaN
1                                 NaN                                 NaN
2                                 NaN                                 NaN
3                                 NaN                                 NaN
4                                 NaN                                 NaN

  1_author_affs_consolidated_0_scopus 1_author_affs_consolidated_1_scopus  \
0                                 NaN                                 NaN
1                                 NaN                                 NaN
2                                 NaN                                 NaN
3                                 NaN                                 NaN
4                                 NaN                                 NaN

  2_author_affs_consolidated_0_scopus 2_author_affs_consolidated_1_scopus  \
0                                 NaN                                 NaN
1                                 NaN                                 NaN
2                                 NaN                                 NaN
3                                 NaN                                 NaN
4                                 NaN                                 NaN

  3_author_affs_consolidated_0_scopus
0                                 NaN
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN

In [69]:
consolidated_master_merged.columns.values

array(['Article_ID', 'year_master', 'authors', 'content_type_master',
       'Unnamed: 0', 'Journal_Name', 'Authors_count', 'Authors_list',
       'content_type', 'stable_url', 'Ref_type', 'ref_string',
       'ref_string_clean1', 'year', '0_author_affs',
       '0_author_affs_consolidated', '0_author_affs_consolidated_0',
       '0_author_affs_consolidated_1', '0_author_affs_consolidated_2',
       '0_author_affs_consolidated_3', '1_author_affs',
       '1_author_affs_consolidated', '1_author_affs_consolidated_0',
       '1_author_affs_consolidated_1', '2_author_affs',
       '2_author_affs_consolidated', '2_author_affs_consolidated_0',
       '2_author_affs_consolidated_1', '2_author_affs_consolidated_2',
       '3_author_affs', '3_author_affs_consolidated',
       '3_author_affs_consolidated_0', '3_author_affs_consolidated_1',
       '4_author_affs', '4_author_affs_consolidated',
       '4_author_affs_consolidated_0', '5_author_affs',
       '5_author_affs_consolidated'], dtype=object)

In [70]:
# Merging the masterfile onto the new melted file to get additional data
consolidated_master_merged['Article_ID'] = consolidated_master_merged['Article_ID'].astype('str')
consolidated_master_scopus_merged = consolidated_master_merged.merge(RES_scopus, how = 'left', on = 'Article_ID')

consolidated_master_scopus_merged = consolidated_master_scopus_merged.sort_values(by=['year_master'])
consolidated_master_scopus_merged = consolidated_master_scopus_merged.reset_index(drop = True)
for i in range(len(consolidated_master_merged)):
#for i in range(2,4):
    print(consolidated_master_scopus_merged.iloc[i]['Article_ID'])
    print(consolidated_master_scopus_merged.loc[i,'0_author_affs_consolidated_0'])
    if pd.isna(consolidated_master_scopus_merged.iloc[i]['0_author_affs_consolidated_0']):
        print('n')
        consolidated_master_scopus_merged.loc[i,'Manual'] = consolidated_master_scopus_merged.loc[i,'Manual']
        consolidated_master_scopus_merged.loc[i,'0_author_affs_consolidated_0'] = consolidated_master_scopus_merged.loc[i,'0_author_affs_consolidated_0_scopus']
        consolidated_master_scopus_merged.loc[i,'0_author_affs_consolidated_1'] = consolidated_master_scopus_merged.loc[i,'0_author_affs_consolidated_1_scopus']
        consolidated_master_scopus_merged.loc[i,'0_author_affs_consolidated_2'] = consolidated_master_scopus_merged.loc[i,'0_author_affs_consolidated_2_scopus']
        consolidated_master_scopus_merged.loc[i,'1_author_affs_consolidated_0'] = consolidated_master_scopus_merged.loc[i,'1_author_affs_consolidated_0_scopus']
        consolidated_master_scopus_merged.loc[i,'1_author_affs_consolidated_1'] = consolidated_master_scopus_merged.loc[i,'1_author_affs_consolidated_1_scopus']
        consolidated_master_scopus_merged.loc[i,'2_author_affs_consolidated_0'] = consolidated_master_scopus_merged.loc[i,'2_author_affs_consolidated_0_scopus']
        consolidated_master_scopus_merged.loc[i,'2_author_affs_consolidated_1'] = consolidated_master_scopus_merged.loc[i,'2_author_affs_consolidated_1_scopus']
        consolidated_master_scopus_merged.loc[i,'3_author_affs_consolidated_0'] = consolidated_master_scopus_merged.loc[i,'3_author_affs_consolidated_0_scopus']
  #      consolidated_master_scopus_merged.loc[i,'4_author_affs_consolidated_0'] = consolidated_master_scopus_merged.loc[i,'4_author_affs_consolidated_0_scopus']
 #       consolidated_master_scopus_merged.loc[i,'5_author_affs_consolidated_0'] = consolidated_master_scopus_merged.loc[i,'5_author_affs_consolidated_0_scopus']
  #      consolidated_master_scopus_merged.loc[i,'6_author_affs_consolidated_0'] = consolidated_master_scopus_merged.loc[i,'6_author_affs_consolidated_0_scopus']
        print(consolidated_master_scopus_merged.iloc[i]['0_author_affs_consolidated_0'])
        print(consolidated_master_scopus_merged.iloc[i]['0_author_affs_consolidated_0_scopus'])

2967475
Cambridge Massachusetts United States (City)
2967408
nan
n
London United Kingdom (City)
London United Kingdom (City)
2967408
nan
n
nan
nan
2967405
Chicago Illinois United States (City), Illinois
2967406
London United Kingdom (City)
2967407
London United Kingdom (City)
2967409
London United Kingdom (City)
2967472
Hague Holland (City)
2967473
Cambridge United Kingdom (City)
2967404
London United Kingdom (City)
2967403
Dundee United Kingdom (City)
2967402
Birmingham United Kingdom(City)
2967474
Columbus Ohio United States (CIty)
2967414
Manchester United Kingdom(City)
2967415
Dundee United Kingdom (City)
2967416
London United Kingdom (City)
2967413
Manchester United Kingdom(City)
2967418
London United Kingdom (City)
2967419
Chicago Illinois United States (City)
2967417
Ames Iowa United States (City), USA
2967464
London United Kingdom (City)
2967601
University Of Oxford
2967469
Chicago Illinois United States (City), Illinois, USA
2967468
Edinburgh United Kingdom (City)
2967467
Manchester United Kingdom(City)
2967466
Cambridge Massachusetts United States (City)
2967470
Ames Iowa United States (City), USA
2967465
Presibury United Kingdom (City)
2967602
London United Kingdom (City)
2967635
Nottingham United Kingdom (City)
2967600
Manchester United Kingdom(City)
2967598
nan
n
nan
nan
2967640
nan
n
Washington United States (City)
Washington United States (City)
2967638
Cambridge United Kingdom (City)
2967637
Cambridge Massachusetts United States (City)
2967636
Cambridge United Kingdom (City)
2967599
Glasgow United Kingdom (City)
2967639
nan
n
nan
nan
2967664
London United Kingdom (City)
2967497
University Of Oxford
2967667
Nottingham United Kingdom (City)
2967666
London United Kingdom (City)
2967665
Manchester United Kingdom(City)
2967498
Ames Iowa United States (City)
2967494
London United Kingdom (City)
2967496
Glasgow United Kingdom (City)
2967495
London United Kingdom (City)
2967663
Ames Iowa United States (City)
2967493
nan
n
nan
nan
2967492
nan
n
London United Kingdom (City)
London United Kingdom (City)
2967515
Manchester United Kingdom(City)
2967520
nan
n
Stillwater United States (City)
Stillwater United States (City)
2967518
University Of Oxford
2967517
Manchester United Kingdom(City)
2967519
Lichuang China (City)
2967516
Manchester United Kingdom(City)
2967427
Manchester United Kingdom(City)
2967426
University Of Oxford
2967425
Stockholm Sweden (City)
2967428
Cambridge United Kingdom (City)
2967429
London United Kingdom (City)
2296097
Cambridge United Kingdom (City)
2296014
Cambridge United Kingdom (City)
2296013
Cambridge Massachusetts United States (City)
2296095
Rennes (France)
2296012
Birmingham United Kingdom(City)
2296011
London United Kingdom (City)
2296098
Montreal Canada (City)
2296096
Madrid Spain (City)
2295970
Cambridge Massachusetts United States (City)
2296094
University Of Oxford
2296093
Washington United States (City)
2296092
Birmingham United Kingdom(City)
2295971
Bristol United Kingdom (City)
2295968
London United Kingdom (City)
2295967
Manchester United Kingdom(City)
2295969
University Of Oxford
2296112
University Of Oxford
2296040
London United Kingdom (City)
2296114
London United Kingdom (City)
2296113
Washington United States (City)
2296042
nan
n
nan
nan
2296036
Vienna Austria (City)
2296039
Glasgow United Kingdom (City)
2296038
University Of Oxford
2296037
University Of Oxford
2296111
Princeton University
2295759
Vienna Austria (City)
2295757
New York (City)
2295756
Cambridge Massachusetts United States (City)
2295755
Rome Italy (City)
2295754
London United Kingdom (City)
2296090
Cambridge Massachusetts United States (City)
2296087
University Of Oxford
2296086
University Of Oxford
2296088
University Of Oxford
2295753
Cambridge Massachusetts United States (City)
2295924
Sydney Austrailia (City)
2295921
nan
n
nan
nan
2295929
University Of Oxford
2295928
Manchester United Kingdom(City)
2295926
Singapore (Country)
2295923
nan
n
Cambridge Massachusetts United States (City)
Cambridge Massachusetts United States (City)
2295925
London United Kingdom (City)
2295998
nan
n
Cambridge Massachusetts United States (City)
Cambridge Massachusetts United States (City)
2295997
Cambridge Massachusetts United States (City)
2295922
Auckland New Zealand (City)
2295996
Chicago United States (City)
2295995
University Of Oxford
2295994
London United Kingdom (City)
2295993
Brussels Belgium (City)
2296141
Brussels Belgium (City)
2296142
University Of Oxford
2296140
Manchester United Kingdom(City)
2296139
London United Kingdom (City)
2296143
London United Kingdom (City)
2295718
Oslo Norway (City)
2295717
Aarhus Denmark (City)
2295716
University Of Oxford
2295715
United Nations
2295919
London United Kingdom (City)
2295917
Montreal Canada (City)
2295790
nan
n
nan
nan
2295915
Cambridge United Kingdom (City)
2295791
University Of Oxford
2295918
Oslo Norway (City)
2295720
nan
n
nan
nan
2295719
Manchester United Kingdom(City)
2295916
Cambridge United Kingdom (City)
2295788
New Haven Connecticut United States (CIty)
2296276
New York (City)
2295870
Cambridge United Kingdom (City)
2295786
Cambridge United Kingdom (City)
2295789
Northfiled Minnesota United States (City)
2296277
University Of Oxford
2296278
Princeton University
2296279
Washington United States (City)
2296280
Basle Switzerland (City)
2296275
London United Kingdom (City)
2295866
Münster Germany (City)
2295867
nan
n
Uppsala Sweden (City)
Uppsala Sweden (City)
2295868
New Haven Connecticut United States (CIty)
2295869
New Haven Connecticut United States (CIty)
2295787
New Haven Connecticut United States (CIty)
2295865
Ann Arbor Michigan United States (City)
2295797
Singapore (Country)
2296103
Cambridge Massachusetts United States (City)
2295798
University Of Oxford
2295800
nan
n
nan
nan
2295801
Copenhagen Denmark (City)
2296104
University Of Oxford
2296105
Jerusalem Israel (City)
2296106
New York United States (City)
2295796
nan
n
Williamstown United States (City)
Williamstown United States (City)
2295799
nan
n
nan
nan
2296107
Dublin United Kingdom (City)
2295977
New York United States (City)
2295980
nan
n
Evanston United States (City)
Evanston United States (City)
2295979
Stanford California United States (City)
2295978
University Of Oxford
2295975
Glasglow United Kingdom (City)
2295795
Cambridge United Kingdom (City)
2295976
Cambridge Massachusetts United States (City)
2295974
Cambridge Massachusetts United States (City)
2295973
Michigan United States (State)
2295794
University Of Oxford
2296265
College Park Maryland United States (City)
2296272
nan
n
nan
nan
2296269
Washington United States (City)
2296268
Cambridge United Kingdom (City)
2296267
Cambridge Massachusetts United States (City)
2296266
nan
n
Cambridge Massachusetts United States (City)
Cambridge Massachusetts United States (City)
2296271
Jerusalem Israel (City)
2296270
Cambridge Massachusetts United States (City)
2295739
Nottingham United Kingdom (City)
2295738
Cambridge Massachusetts United States (City)
2295737
nan
n
Cambridge Massachusetts United States (City)
Cambridge Massachusetts United States (City)
2295736
Birmingham United Kingdom (City)
2295735
Cambridge Massachusetts United States (City)
2295740
Cambridge Massachusetts United States (City)achusetts
2295741
University Of Oxford
2296019
University Of Oxford
2296018
Cambridge Massachusetts United States (City)
2296016
Amsterdam Netherlands (City)
2296165
University Of Oxford
2296017
Cardiff United Kingdom (CIty)
2296162
Cambridge Massachusetts United States (City)
2296159
New York United States (City)
2296160
Pittsburgh Pennsylvania United States (City)
2296158
nan
n
nan
nan
2295850
nan
n
Washington United States (City)
Washington United States (City)
2296163
Nottingham United Kingdom (City)
2295849
Ottawa Canada (City)
2296161
Cambridge Massachusetts United States (City)
2295887
Stanford California United States (City)
2296021
Jerusalem Israel (City)
2295890
Tallahassee Florida United States (City)
2295847
University Of Oxford
2295845
Williamstown Massachusetts United States (City)
2295844
nan
n
nan
nan
2295843
Cambridge Massachusetts United States (City)
2295893
Swansea United Kingdom (City)
2295892
Nottingham United Kingdom (City)
2295891
Baltimore Maryland (City)
2295848
Auckland New Zealand (City)
2295889
New York United States (City)
2295846
Michigan United States (State)
2295886
London United Kingdom (City)
2295885
University Of Oxford
2295884
nan
n
nan
nan
2295888
Melbourne Australia (City)
2296003
University Of Oxford
2296261
Cambridge Massachusetts United States (City)
2296259
London United Kingdom (City)
2296258
University Of Oxford
2296257
London United Kingdom (City)
2296256
Cambridge Massachusetts United States (City)
2296008
Paris France (City)
2296005
Cambridge Massachusetts United States (City)
2296006
Cambridge Massachusetts United States (City)
2296007
Cambridge Massachusetts United States (City)
2295780
nan
n
Montreal Canada (City)
Montreal Canada (City)
2296002
Cambridge Massachusetts United States (City)
2295781
New Haven Connecticut United States (City)
2295770
Durham, North Carolina United States (City)
2295771
Toronoto Canada (City)
2295779
Glasglow United Kingdom (City)
2295773
nan
n
Brisbane Australia (City)
Brisbane Australia (City)
2295774
Osaka Japan (City)
2295772
Cambridge Massachusetts United States (City)
2296288
Belfast Ireland (City)
2296219
Leeds United Kingdom (City)
2296226
Ames Iowa United States (City)
2296225
Geneva Switzerland (CIty)
2296224
University Of Oxford
2296223
Ibadan Nigeria (City)
2296222
Stanford California United States (City)
2296221
Stanford California United States (City)
2296220
University College Of North Staffordshire
2296227
University Of Oxford
2295874
Bristol United Kingdom (City)
2295877
London United Kingdom (City)
2296285
Delhi India (City)
2296284
Cambridge Massachusetts United States (City)
2295878
Cambridge United Kingdom (City)
2296287
University Of Oxford
2295876
Cambridge United Kingdom (City)
2296286
London United Kingdom (City)
2295873
Sala Sweden (CIty)
2295875
Brunswick Maine United States (City)
2296147
nan
n
Auckland New Zealand (City)
Auckland New Zealand (City)
2296296
Osaka Japan (City)
2296298
London United Kingdom (City)
2296299
Nottingham United Kingdom (City)
2296300
Toronoto Canada (City)
2296295
Michigan United States (State)
2296149
Nottingham United Kingdom (City)
2296148
Stanford California United States (City)
2296294
New York United States (City)
2296151
Nottingham United Kingdom (City)
2296152
Durham North Carolina United States (City)
2296153
Birmingham United Kingdom (City)
2296154
University Of Oxford
2296146
Chicago Illinois United States (City)
2296297
London United Kingdom (City)
2295729
nan
n
nan
nan
2295732
Cambridge Massachusetts United States (City)
2295731
Cambridge Massachusetts United States (City)
2295730
University Of Oxford
2296293
Cambridge Massachusetts United States (City)
2295728
New Haven Conneticut United States (City)
2295727
University Of Oxford
2295726
Bloomington Indiana United States (City)
2295725
University Of Oxford
2296292
Cambridge Massachusetts United States (City)
2295723
Paris France (City)
2295722
London United Kingdom (City)
2295724
Toronoto Canada (City)
2296236
Nottingham United Kingdom (City)
2296240
London United Kingdom (City)
2296239
University Of Oxford
2296238
Osaka Japan (City)
2296235
Cambridge Massachusetts United States (City)
2296234
Cambridge Massachusetts United States (City)
2296233
London United Kingdom (City)
2296232
Swarthmore Pennsylvania United States (City)
2296237
Bloomington Indiana United States (City)
2295762
Bradford United Kingdom (City)
2296071
Tasmania Australia (City)
2296072
London United Kingdom (City)
2296073
Auckland New Zealand (City)
2295761
Cambridge Massachusetts United States (City)
2295765
University Of Bristol United Kingdom (City)
2295763
University Of Oxford
2295766
Urbana Illionis (City)
2295767
Canberra Australia (CIty)
2296069
nan
n
nan
nan
2296070
University Of Oxford
2295764
Exeter United States (City)
2296068
Liverpool United Kingdom (City)
2296067
Durham, North Carolina United States (City)
2296066
Sheffield United Kingdom (City)
2296065
University Of Sheffield
2296125
London United Kingdom (City)
2296121
Cambridge Massachusetts United States (City)
2296120
nan
n
University Of Cambridge
University Of Cambridge
2296119
Cambridge Massachusetts United States (City)
2296118
Edinburgh United Kingdom (City)
2296117
New York United States (City)
2296064
University Of Oxford
2296215
nan
n
nan
nan
2296211
Vancouver Canada (City)
2296210
Exeter United Kingdom (City)
2296209
Rotterdam Netherlands (City)
2296212
Sheffield United Kingdom (CIty)
2296208
Oslow Norway (City)
2296206
Cambridge Massachusetts United States (City)
2296205
New Haven Conneticut United States (City)
2296216
nan
n
nan
nan
2296204
nan
n
nan
nan
2295990
University Of Oxford
2296207
Massachusetts Institute Of Technology
2295991
Cambridge Massachusetts United States (City)
2295858
London United Kingdom (City)
2295987
Munich Germany
2295861
Washington United States (CIty)
2295983
Birmingham United Kingdom (City)
2295862
Sheffield United Kingdom (City)
2295859
University Of Oxford
2295986
Providence Rhode Island United States (City)
2295985
Southampton United Kingdom (City)
2295856
Aberdeen United Kingdom (City)
2295855
New York United States (City)
2295854
London United Kingdom (City)
2295984
Cambridge Massachusetts United States (City)
2295857
University of Oxford
2295749
Minnesota United States (State)
2295746
Stanford California United States (City)
2296173
Cambridge Massachusetts United States (City)
2296172
Cambridge Massachusetts United States (City)
2296171
Makerere College
2296170
London United Kingdom (City)
2296169
Birmingham United Kingdom (City)
2296168
London United Kingdom (City)
2295750
London United Kingdom (City)
2295748
nan
n
nan
nan
2295747
London United Kingdom (City)
2295745
New Haven Conneticut United States (City)
2296051
nan
n
London United Kingdom (City)
London United Kingdom (City)
2296050
London United Kingdom (City)
2296049
University Of Oxford
2296048
Belfast Ireland (City)
2296047
Michigan United States (State)
2296046
Cambridge Massachusetts United States (City)
2296045
Kingston Jamaica (City)
2295744
University Of Oxford
2296084
London United Kingdom (City)
2296128
Jamaica (Country)
2296129
Harvard University
2296130
Oslo Norway (City)
2296081
Osaka Japan (City)
2296132
New Haven Conneticut United States (City)
2296134
University Of Oxford
2296135
Cyprus Middle East (City)
2296083
nan
n
Khartoum Japan (City)
Khartoum Japan (City)
2296131
nan
n
Osaka Japan (City)
Osaka Japan (City)
2296082
Jamaica (Country)
2296078
Ucb
2296080
Stanford California United States (City)
2296249
Pittsburgh Pennslyvania United States (City)
2296245
California United States (State)
2296247
Northwestern University
2296248
Cambridge Massachusetts United States (City)
2296244
Melbourne Australia (City)
2296251
Cambridge Massachusetts United States (City)
2296252
nan
n
nan
nan
2296076
nan
n
nan
nan
2296077
University Of Minnesota
2296136
Frankfort Germany (City)
2295710
Cambridge Massachusetts United States (City)
2295709
UCB
2295712
nan
n
Berkeley California United States (City)
Berkeley California United States (City)
2295947
London United Kingdom (City)
2295711
Birmingham United Kingdom (City)
2295705
University Of Oxford
2295949
University Of Oxford
2295708
Berkeley California United States (City)
2295707
Ucb
2295948
Stanford, California United States (State)
2295706
Osaka Japan (City)
2295946
Stanford California United States (City)
2296185
Manchester United Kingdom(City)
2296184
Toronoto Canada (City)
2296181
Cambridge Massachusetts United States (City)
2296183
Cambridge Massachusetts United States (City)
2295944
Paris France (City)
2296180
Stanford University
2296179
Manchester United Kingdom(City)
2296178
London United Kingdom (City)
2296182
Ann Arbor Michigan United States (City)
2295945
Rochester New York United States (City)
2295957
Cambridge Massachusetts United States (City)
2295955
Cambridge Massachusetts United States (City)
2295820
Bristol United Kingdom (City)
2295819
Lafayette Indiana United States (City)
2295821
Durham, North Carolina United States (City)
2295817
London United Kingdom (City)
2295816
Rangoon Myanmar (City)
2295960
Cambridge Massachusetts United States (City)
2295959
University Of Oxford
2295958
Cambridge Massachusetts United States (City)
2295818
Edinburgh United Kingdom (City)
2295956
Cambridge Massachusetts United States (City)
2295954
Cambridge Massachusetts United States (City)
2295953
Cambridge Massachusetts United States (City)
2295952
Stanford University
2296303
Cambridge Massachusetts United States (City)
2296304
New Haven Conneticut United States (City)
2296306
London United Kingdom (City)
2296305
Stanford University
2296308
Birmingham United Kingdom (City)
2296309
Minneapolis Minnesota United States (City)
2296310
Cambridge Massachusetts United States (City)
2296312
Birmingham United Kingdom (City)
2296307
Osaka Japan (City)
2296028
Lafayette Indiana United States (City)
2296034
Berkeley California United States (City)
2296033
Chicago Illinois United States (City)
2296031
University Of Oxford
2296030
Perth Australia (City)
2296032
Chicago Illinois United States (City)
2295810
Bloomington Indiana United States (City)
2296026
Honolulu Hawaii (City)
2296025
Birmingham United Kingdom (City)
2295812
Birmingham United Kingdom (City)
2295811
Exeter United Kingdom (City)
2295807
Tokyo Japan (City)
2296027
Lafayette Indiana United States (City)
2295808
Stanford University
2296321
Cambridge Massachusetts United States (City)
2295806
Pittsburgh Pennslyvania United States (City)
2296029
Cambridge Massachusetts United States (City)
2296322
nan
n
nan
nan
2295805
Chicago Illinois United States (City)
2295804
Pittsburgh Pennslyvania United States (City)
2296324
Pune India (City)
2296323
New Haven Conneticut United States (City)
2296319
Manchester United Kingdom(City)
2296318
New Haven Conneticut United States (City)
2296317
Rochester New York (City)
2296315
Cambridge Massachusetts United States (City)
2296320
Cambridge Massachusetts United States (City)
2296316
Cambridge Massachusetts United States (City)
2295934
Tokyo Japan (City)
2295941
Cambridge Massachusetts United States (City)
2295940
Rochester New York United States (City)
2295938
Pune India (City)
2295937
Baltimore Maryland (City)
2295936
nan
n
nan
nan
2295935
nan
n
nan
nan
2295939
Pune India (City)
2296197
Tokyo Japan (City)
2295933
Osaka Japan (City)
2296200
University Of Bristol
2296199
nan
n
nan
nan
2296198
nan
n
nan
nan
2296196
nan
n
nan
nan
2296195
Tokyo Metropolitan University
2296193
nan
n
nan
nan
2295932
nan
n
nan
nan
2296194
nan
n
nan
nan
2296201
nan
n
nan
nan
2296192
nan
n
nan
nan
2295906
Massachusetts Institute Of Technology
2295909
University Of Delhi
2296188
nan
n
nan
nan
2295912
nan
n
nan
nan
2295911
nan
n
nan
nan
2295910
Tokyo Japan (City)
2295908
University Of Birmingham
2295899
Harvard University
2296189
nan
n
nan
nan
2295903
nan
n
nan
nan
2295902
nan
n
nan
nan
2295901
Stanford University  University
2295900
University Of Minnesota
2295898
Ucb
2295897
London United Kingdom (City)
2295907
University Of York
2296191
nan
n
nan
nan
2296331
National University Of Taiwan
2296333
Australian National University
2296330
nan
n
nan
nan
2296329
London School Of Economics
2296328
nan
n
The University Of Chicago
The University Of Chicago
2296332
University Of Wisconsin- Madison
2296058
Yale University
2296060
UCB
2296059
nan
n
Tokyo Metropolitan University
Tokyo Metropolitan University
2296056
Brown University
2296327
Carnegie Mellon University
2296054
nan
n
Cambridge Massachusetts United States (City)
Cambridge Massachusetts United States (City)
2296061
University of Oxford
2296055
nan
n
University Of Birmingham
University Of Birmingham
2296057
nan
n
nan
nan
2295831
nan
n
nan
nan
2295829
Makerere University College
2295827
Yale University
2295826
University Of Bristol
2295825
University of Oxford
2295836

In [72]:
# Excel output to get an overview of the data
consolidated_master_scopus_merged.head
consolidated_master_scopus_merged.to_excel('/Users/MattJohnson/Desktop/Affiliations/2_Extracting affilitations/3_consolidation/RES/Scopus/RES_master scopus merge.xlsx')

# Merging on scopus post 1981 to check for affiliations

In [19]:
# Read in the consolidated data
import pandas as pd
import numpy as np
#for i in range(1577,1578):
RES_consolidated_master_scopus_merged = pd.read_excel('/Users/MattJohnson/Desktop/Affiliations/2_Extracting affilitations/3_consolidation/RES/Scopus/RES_master merge.xlsx') 

#RES_consolidated_master_scopus_merged = RES_consolidated_master_scopus_merged.loc[RES_consolidated_master_scopus_merged['year_master'] >= 1980]
#RES_consolidated_master_scopus_merged = RES_consolidated_master_scopus_merged.sort_values(by=['year_master'])
#RES_consolidated_master_scopus_merged = RES_consolidated_master_scopus_merged.replace(np.nan, '', regex=True)
print(RES_consolidated_master_scopus_merged.shape)
RES_consolidated_master_scopus_merged['year_master'] = RES_consolidated_master_scopus_merged['year_master'].astype('int')
RES_consolidated_master_scopus_merged['Article_ID'] = RES_consolidated_master_scopus_merged['Article_ID'].astype('int')
RES_consolidated_master_scopus_merged = RES_consolidated_master_scopus_merged.reset_index(drop = True)

RES_consolidated_master_scopus_merged  = RES_consolidated_master_scopus_merged[['Article_ID','year_master','0_author_affs_consolidated_0']]
                                                                                
print(RES_consolidated_master_scopus_merged.shape)
print(RES_consolidated_master_scopus_merged.columns.values)
print(RES_consolidated_master_scopus_merged.head())

(2608, 39)
(2608, 3)
['Article_ID' 'year_master' '0_author_affs_consolidated_0']
   Article_ID  year_master                  0_author_affs_consolidated_0
0     2967475         1940  Cambridge Massachusetts United States (City)
1     2967413         1940               Manchester United Kingdom(City)
2     2967414         1940               Manchester United Kingdom(City)
3     2967415         1940                  Dundee United Kingdom (City)
4     2967416         1940                  London United Kingdom (City)

In [21]:
# Read in the consolidated data
import pandas as pd
import numpy as np
#for i in range(1577,1578):
RES_scopus_for_merge = pd.read_excel('/Users/MattJohnson/Desktop/Affiliations/2_Extracting affilitations/3_consolidation/RES/Scopus/RES_scopus.xlsx') 

for i in range(len(RES_scopus)):
    RES_scopus_for_merge.loc[i,['Article_ID']] = RES_scopus_for_merge.loc[i,['DOI']].to_string().rsplit('/',1)[-1]

#RES_scopus_for_merge = RES_scopus_for_merge.replace(np.nan, '', regex=True)
print(RES_scopus_for_merge.shape)
RES_scopus_for_merge['year'] = RES_scopus_for_merge['year'].astype('int')
#RES_scopus_for_merge['Article_ID'] = RES_scopus_for_merge['Article_ID'].astype('int')
RES_scopus_for_merge = RES_scopus_for_merge.reset_index(drop = True)

RES_scopus_for_merge  = RES_scopus_for_merge[['Article_ID','year','affiliations']]
                                                                                
print(RES_scopus_for_merge.shape)
print(RES_scopus_for_merge.columns.values)
print(RES_scopus_for_merge.head())

(2832, 15)
(2832, 3)
['Article_ID' 'year' 'affiliations']
  Article_ID  year                 affiliations
0    2967407  1940       London, United Kingdom
1    2967407  1940                          NaN
2  7.2.138-a  1940                          NaN
3    2967408  1940       London, United Kingdom
4    7.2.137  1940  Berkeley, CA, United States

In [34]:
# Merging the masterfile onto the new melted file to get additional data
RES_consolidated_master_scopus_merged['Article_ID'] = RES_consolidated_master_scopus_merged['Article_ID'].astype('str')
RES_consolidated_master_scopus_merged_1981 = RES_consolidated_master_scopus_merged.merge(RES_scopus_for_merge, how = 'left', on = 'Article_ID')

RES_consolidated_master_scopus_merged_1981 = RES_consolidated_master_scopus_merged_1981.sort_values(by=['year_master'])
RES_consolidated_master_scopus_merged_1981 = RES_consolidated_master_scopus_merged_1981.reset_index(drop = True)


# Excel output to get an overview of the data
RES_consolidated_master_scopus_merged_1981.head
RES_consolidated_master_scopus_merged_1981.to_excel('/Users/MattJohnson/Desktop/Affiliations/2_Extracting affilitations/3_consolidation/RES/Scopus/RES_consolidated_master_scopus_merged_1981.xlsx')

In [35]:
count = 0
for i in range(len(RES_consolidated_master_scopus_merged_1981)):
#for i in range(2,4):

    if pd.isna(RES_consolidated_master_scopus_merged_1981.iloc[i]['0_author_affs_consolidated_0']) and not (pd.isna(RES_consolidated_master_scopus_merged_1981.iloc[i]['affiliations'])):
        print('blank')
        print(RES_consolidated_master_scopus_merged_1981.iloc[i]['Article_ID'])
        print(RES_consolidated_master_scopus_merged_1981.loc[i,'0_author_affs_consolidated_0'])
        print(RES_consolidated_master_scopus_merged_1981.loc[i,'affiliations'])
        count = count +1
        print(count)
    #else:
       # RES_consolidated_master_scopus_merged_1981.drop(RES_consolidated_master_scopus_merged_1981.index[i], inplace = True)
        #RES_consolidated_master_scopus_merged_1981.loc[i,'0_author_affs_consolidated_0'] = RES_consolidated_master_scopus_merged_1981.loc[i,'0_author_affs_consolidated_0_scopus']
 #       consolidated_master_scopus_merged.loc[i,'5_author_affs_consolidated_0'] = consolidated_master_scopus_merged.loc[i,'5_author_affs_consolidated_0_scopus']
  #      consolidated_master_scopus_merged.loc[i,'6_author_affs_consolidated_0'] = consolidated_master_scopus_merged.loc[i,'6_author_affs_consolidated_0_scopus']
        #print(RES_consolidated_master_scopus_merged_1981.iloc[i]['0_author_affs_consolidated_0'])
        #print(RES_consolidated_master_scopus_merged_1981.iloc[i]['0_author_affs_consolidated_0_scopus'])
RES_consolidated_master_scopus_merged_1981.iloc[[0]].head()
RES_consolidated_master_scopus_merged_1981.shape

blank
2967408
nan
London, United Kingdom
1
blank
2967640
nan
Washington, DC, United States
2
blank
2967492
nan
London, United Kingdom
3
blank
2967520
nan
Stillwater, OK, United States
4
blank
2295923
nan
Cambridge, United Kingdom
5
blank
2295998
nan
Cambridge, United States
6
blank
2295867
nan
Uppsala, Sweden
7
blank
2295796
nan
Williamstown, MA, United States
8
blank
2295980
nan
Evanston, IL, United States
9
blank
2296266
nan
Cambridge, MA, United States
10
blank
2295737
nan
Cambridge, United States
11
blank
2295850
nan
a--London, United Kingdom
b--Oxford, United States
12
blank
2295780
nan
Montreal, Canada
13
blank
2295773
nan
Brisbane, Australia
14
blank
2296147
nan
Auckland, New Zealand
15
blank
2296120
nan
Botany School, University of Cambridge, United Kingdom
16
blank
2296051
nan
London, United Kingdom
17
blank
2296083
nan
Khartoum, Sudan
18
blank
2296131
nan
Osaka, Japan
19
blank
2295712
nan
Berkeley, CA, United States
20
blank
2296328
nan
The University of Chicago, United States
21
blank
2296059
nan
Tokyo Metropolitan University, Japan
22
blank
2296054
nan
Cambridge, United States
23
blank
2296055
nan
University of Birmingham, United Kingdom
24
blank
2295837
nan
Purdue University, Lafayette, United States
25
blank
2974435
nan
a--Massachusetts Institute of Technology, United States
b--Cowles Foundation for Research in Economics, Yale University, United States
c--Institut für Bildungsforschung, Berlin, United States
26
blank
2974440
nan
The Hebrew University, Jerusalem, Israel
27
blank
2296642
nan
Cambridge, United States
28
blank
2974436
nan
The Hebrew University, Jerusalem, Israel
29
blank
2974414
nan
Netherlands School of Economics, Netherlands
30
blank
2974430
nan
United Nations, New York, United States
31
blank
2974425
nan
Massachusetts Institute of Technology, United States
32
blank
2974413
nan
London Graduate School of Business Studies, University of Manchester, United Kingdom
33
blank
2296809
nan
United Nations, New York, United States
34
blank
2296810
nan
CERMAP, France
35
blank
2296678
nan
University of Stockholm, Sweden
36
blank
2296560
nan
The RAND Corporation, United States
37
blank
2296554
nan
Massachusetts Institute of Technology, United States
38
blank
2974407
nan
Brown University, United States
39
blank
2974404
nan
Massachusetts Institute of Technology, United States
40
blank
2296427
nan
Osaka University, Japan
41
blank
2296501
nan
Brown University, United States
42
blank
2296417
nan
University of Wisconsin, Madison, United States
43
blank
2296409
nan
London, United Kingdom
44
blank
2296727
nan
University of Toronto, Canada
45
blank
2296629
nan
United States
46
blank
2296392
nan
University of California, Berkeley, United States
47
blank
2296391
nan
Air Force Institute of Technology, United States
48
blank
2296584
nan
CORE, United States
49
blank
2297219
nan
Hebrew University, University of Illinois, Israel
50
blank
2297223
nan
London School of Economics, United Kingdom
51
blank
2297342
nan
Insee, Paris, France
52
blank
2297254
nan
School of Business Administration, University of California, Berkeley, United States
53
blank
2296919
nan
London School of Economics, London, United Kingdom
54
blank
2296915
nan
Harvard University, United States
55
blank
2296923
nan
University of Tsukuba, Japan
56
blank
2296929
nan
Virginia Polytechnic Institute and State University, United States
57
blank
2296928
nan
Johns Hopkins University, United States
58
blank
2296927
nan
a--Harvard University, United States
b--Northwestern University, United States
59
blank
2296926
nan
a--University of Birmingham, United Kingdom
b--La Trobe University, Australia
60
blank
2296925
nan
Columbia University and University of Essex, United States
61
blank
2296924
nan
Tohoku University, Japan
62
blank
2296930
nan
University of Washington, United States
63
blank
2296921
nan
University of British Columbia, CA, Canada
64
blank
2296920
nan
University of York, United Kingdom
65
blank
2296918
nan
a--University of British Columbia, Canada
b--Bank of Canada, Canada
66
blank
2296917
nan
a--London School of Economics, United Kingdom
b--Stanford University, United States
c--Massachusetts Institute of Technology, United States
67
blank
2296922
nan
a--University of Canterbury, New Zealand
b--Boston College, United States
68
blank
2296916
nan
Nuffield College, Oxford, United States
69
blank
2297198
nan
a--Northwestern University, United States
b--Princeton University, United States
70
blank
2297196
nan
London School of Economics, United Kingdom
71
blank
2297195
nan
University of Chicago, United States
72
blank
2297160
nan
a--University of York, United Kingdom
b--University of Southampton, United Kingdom
73
blank
2297159
nan
a--Seikei University, Japan
b--Hitotsubashi University, Japan
74
blank
2297158
nan
University of Southern California, United States
75
blank
2297161
nan
a--Australian National University, Australia
b--Bureau of Agricultural Economics, Canberra, Australia
76
blank
2296893
nan
London School of Economics, United Kingdom
77
blank
2297117
nan
Australian National University, Australia
78
blank
2297201
nan
McMaster University, Canada
79
blank
2297202
nan
University of Tsukuba and Yale University, United States
80
blank
2297153
nan
California Institute of Technology, United States
81
blank
2297199
nan
New York University, United States
82
blank
2297207
nan
University of Massachusetts, Amherst, United States
83
blank
2297157
nan
Norwegian School of Economics and Business Administration, Bergen, Norway
84
blank
2297156
nan
Princeton University, United States
85
blank
2297155
nan
London School of Economics, United Kingdom
86
blank
2297154
nan
CEREMADE, France
87
blank
2297210
nan
Universita Cattolica, Milan, Italy
88
blank
2297209
nan
Trinity College, Cambridge, United Kingdom
89
blank
2297208
nan
Universitat Karlsruhe, Germany
90
blank
2297152
nan
a--University of California, Los Angeles, United States
b--The Hebrew University of Jerusalem and the Falk Institute, Israel
91
blank
2297118
nan
Birkbeck College, United Kingdom
92
blank
2297203
nan
State University of New York, Stony Brook, United States
93
blank
2297119
nan
London School of Economics, United Kingdom
94
blank
2297123
nan
University of Reading, United Kingdom
95
blank
2297121
nan
University of British Columbia, Canada
96
blank
2296888
nan
a--Aoyama Gakuin University, Japan
b--University of Houston, United States
97
blank
2296886
nan
Princeton University, United States
98
blank
2296885
nan
University of Hull, United Kingdom
99
blank
2296884
nan
a--University of Pennsylvania, United States
b--University of Illinois and C.O.R.E., United States
100
blank
2296883
nan
London School of Economics, United Kingdom
101
blank
2296882
nan
Queen’s University, Canada
102
blank
2297166
nan
Texas A and M University, United States
103
blank
2296880
nan
University of California, Los Angeles, United States
104
blank
2296879
nan
Brown University, United States
105
blank
2297165
nan
The University of Western Australia, Australia
106
blank
2297164
nan
State University of New York, Stony Brook, United States
107
blank
2297163
nan
University of Santa Clara, United States
108
blank
2296889
nan
Stanford University, United States
109
blank
2296887
nan
University of York, United Kingdom
110
blank
2297122
nan
University of Toronto, Canada
111
blank
2297124
nan
Institut National de la Statistique et des Etudes Economiques, Tunisia
112
blank
2297120
nan
Essex University and Columbia University, United States
113
blank
2296881
nan
London School of Economics, United Kingdom
114
blank
2297126
nan
University of Kentucky, United States
115
blank
2297125
nan
University of Santa Clara, United States
116
blank
2297128
nan
a--Princeton University, United States
b--Columbia University and C.O.R.E., United States
117
blank
2297129
nan
Kyota Sangyo University, Japan
118
blank
2297130
nan
University of Bremen, Germany
119
blank
2297131
nan
CORE and Duke University, United States
120
blank
2296892
nan
Institut National de la Statistique et des Etudes Economiques, Tunisia
121
blank
2297132
nan
University of Groningen, Netherlands
122
blank
2297127
nan
a--University of British Columbia, Canada
b--University of California, United States
123
blank
2297137
nan
Harvard University, United States
124
blank
2297138
nan
Yale University, United States
125
blank
2297139
nan
London School of Economics, United Kingdom
126
blank
2297140
nan
University of Southampton, United Kingdom
127
blank
2297141
nan
University of California, San Diego, United States
128
blank
2297147
nan
California Institute of Technology, United States
129
blank
2297143
nan
Yale University, United States
130
blank
2297144
nan
a--University of Gdansk, Poland
b--Princeton University, United States
131
blank
2297148
nan
National Bureau of Economic Research, United States
132
blank
2297145
nan
Institute for Defense Analysis, United States
133
blank
2297136
nan
London School of Economics, United Kingdom
134
blank
2297142
nan
University of Birmingham, United Kingdom
135
blank
2297191
nan
a--Hebrew University, NBER, Israel
b--Harvard University, NBER, United States
136
blank
2297273
nan
Princeton University, United States
137
blank
2297189
nan
Columbia University, United States
138
blank
2297190
nan
a--Harvard University, National Bureau of Economic Research, United States
b--Massachusetts Institute of Technology, National Bureau of Economic Research, United States
139
blank
2297272
nan
California Institute of Technology, United States
140
blank
2297274
nan
Rutgers—The State University, National Opinion Research Center, United States
141
blank
2297275
nan
London School of Economics, United Kingdom
142
blank
2297276
nan
a--University of Canterbury and University of Texas, Austin, United States
b--Boston College, United States
143
blank
2297184
nan
United Kingdom
144
blank
2297185
nan
a--Hebrew University, NBER, United States
b--Harvard University, NBER, United States
145
blank
2297186
nan
Centre for Labour Economics, London School of Economics, United Kingdom
146
blank
2297187
nan
London School of Economics, United Kingdom
147
blank
2297188
nan
a--Princeton University, United States
b--University of Chicago, United States
148
blank
2297278
nan
Churchill College, Cambridge, United States
149
blank
2297270
nan
a--University of Canterbury, New Zealand
b--Flinders University, Australia
150
blank
2297146
nan
The University of Rochester, United States
151
blank
2297271
nan
Massachusetts Institute of Technology, United States
152
blank
2297277
nan
Delhi School of Economics, CORE and CEME Brussels, India
153
blank
2297269
nan
a--London School of Economics, United Kingdom
b--Ecole Normale Supérieure, C.N.R.S., Paris, United Kingdom
154
blank
2297285
nan
London School of Economics, United Kingdom
155
blank
2297361
nan
University of Minnesota, United States
156
blank
2297362
nan
Norwegian School of Economics and Business Administration, United Kingdom
157
blank
2297363
nan
University of Bonn, Germany
158
blank
2297365
nan
University of Toronto, Canada
159
blank
2297372
nan
London School of Economics, United Kingdom
160
blank
2297367
nan
California Institute of Technology, United States
161
blank
2297368
nan
University of New South Wales, Australia
162
blank
2297369
nan
Tohoku University, Japan
163
blank
2297370
nan
a--Yale University, Princeton University, United States
b--The Johns Hopkins University, United States
c--University of Illinois, United States
164
blank
2297360
nan
University of Toronto, Canada
165
blank
2297366
nan
a--University of Florida, Hebrew University of Jerusalem, United States
b--The Hebrew University of Jerusalem, Israel
166
blank
2297359
nan
Northwestern University, China
167
blank
2297364
nan
University of Amsterdam, Netherlands
168
blank
2297295
nan
a--University of Chicago, United States
b--Stanford University, United States
169
blank
2297282
nan
a--University of California, San Diego, United States
b--Bell Laboratories, United States
170
blank
2297268
nan
a--University of Florida, United States
b--Carnegie-Mellon University, United States
171
blank
2297284
nan
Massachusetts Institute of Technology, United States
172
blank
2297286
nan
Queen’s University, United States
173
blank
2297283
nan
a--Northwestern University, United States
b--University of California, Berkeley, United States
174
blank
2297288
nan
Princeton University, United States
175
blank
2297287
nan
a--London School of Economics, United Kingdom
b--University of California, Berkeley, United States
c--Princeton University, United States
176
blank
2297289
nan
University of British Columbia, Canada
177
blank
2297290
nan
Massachusetts Institute of Technology, United States
178
blank
2297291
nan
a--INSEE, United States
b--ENSAE, United States
179
blank
2297292
nan
University of Warwick, El Colegio de México, United Kingdom
180
blank
2297293
nan
Universitat Autònoma de Barcelona, United States
181
blank
2297296
nan
University of Manchester, United Kingdom
182
blank
2296954
nan
London School of Economics
183
blank
2297702
nan
a--University of British Columbia, Canada
b--University of California, Los Angeles, United States
184
blank
2297710
nan
Carnegie-Mellon University, United States
185
blank
2297709
nan
a--Yale University, C.O.R.E., United States
b--Columbia University, United States
186
blank
2297708
nan
Columbia University, United States
187
blank
2297707
nan
University of California, Los Angeles, United States
188
blank
2297704
nan
The Hebrew University, Jerusalem, Israel
189
blank
2297703
nan
Georgia State University, United States
190
blank
2297706
nan
University of Pennsylvania, United States
191
blank
2297693
nan
Massachusetts Institute of Technology, United States
192
blank
2297701
nan
a--Churchill College, Cambridge, United Kingdom
b--The World Bank, United Kingdom
c--Princeton University, United States
193
blank
2297690
nan
a--The Hebrew University of Jerusalem, Israel
b--The Maurice Folk Institute for Economic Research, Israel
c--Harvard University, United States
d--The National Bureau of Economic Research, United States
194
blank
2297691
nan
Rutgers University, United States
195
blank
2297712
nan
a--University of British Columbia, Canada
b--Bank of Canada, Canada
196
blank
2297689
nan
a--University of Chicago, United States
b--NORC, United States
c--Columbia University, United States
197
blank
2297695
nan
a--University of Aarhus, Denmark
b--State University of New York, Albany, United States
198
blank
2297696
nan
a--Virginia Polytechnic Institute and State University, United States
b--Columbia University, United States
199
blank
2297697
nan
Universität Göttingen, Germany
200
blank
2297694
nan
a--University of California, Berkeley, United States
b--Bell Laboratories, United States
201
blank
2297687
nan
a--Yale University, United States
b--University of Chicago, United States
c--Carleton University, Canada
202
blank
2297698
nan
University of Alberta, Canada
203
blank
2297688
nan
University of California, Berkeley, United States
204
blank
2297783
nan
The University of British Columbia, Canada
205
blank
2297686
nan
University of Warwick, United Kingdom
206
blank
2297429
nan
a--Harvard University, United States
b--University of Texas, Austin, United States
207
blank
2297437
nan
University of Southern California, United States
208
blank
2297436
nan
Columbia University, United States
209
blank
2297435
nan
University of Toronto, Canada
210
blank
2297432
nan
Stanford University, United States
211
blank
2297431
nan
a--Massachusetts Institute of Technology, United States
b--Indiana University and Northwestern University, United States
212
blank
2297430
nan
University of Chicago, United States
213
blank
2297428
nan
University of California, San Diego, United States
214
blank
2297782
nan
University of Edinburgh, United Kingdom
215
blank
2297433
nan
University of Minnesota, Harvard University, United Kingdom
216
blank
2297785
nan
a--University of Tsukuba, Japan
b--Queen's University, Canada
217
blank
2297784
nan
University of Virginia, United States
218
blank
2297692
nan
a--Rice University, United States
b--University of Minnesota, United States
219
blank
2297781
nan
a--University of Arizona, United States
b--United States
220
blank
2297780
nan
Stanford University, United States
221
blank
2297779
nan
a--Cornell University, United States
b--Cornell University and Economics Research Centre/NORC, United States
c--Northwestern University, United States
d--Northwestern University and Economics Research Centre/NORC, United States
222
blank
2297778
nan
London School of Economics, United Kingdom
223
blank
2297438
nan
University of Exeter, United Kingdom
224
blank
2297787
nan
Southern Methodist University, United States
225
blank
2297786
nan
AT and T Bell Laboratories, United States
226
blank
2297474
nan
London School of Economics, United Kingdom
227
blank
2297668
nan
University of Stockholm, University of Michigan, United States
228
blank
2297737
nan
a--University of Pennsylvania, London School of Economics, United Kingdom
b--University of Bonn, Germany
229
blank
2297654
nan
University of Pennsylvania and Board of Governors of the Federal Reserve System, United States
230
blank
2297635
nan
Institute for International Economic Studies, University of Stockholm, Sweden
231
blank
2297595
nan
a--Universite des Sciences Sociales, Toulouse, United States
b--California Institute of Technology, United States
232
blank
2297594
nan
St. Anne’s College, Oxford, United States
233
blank
2297593
nan
a--Israel Institute of Technology, University of Pittsburgh, United States
b--Israel Institute of Technology, University of Pittsburgh, United States
234
blank
2297592
nan
a--University of California, Berkeley, United States
b--University of Pennsylvania, United States
235
blank
2297591
nan
a--AT and T Bell Laboratories, New York University, United States
b--Northwestern University, United States
c--Harvard University, United States
236
blank
2297590
nan
AT and T Bell Laboratories, United States
237
blank
2297589
nan
a--University of Cambridge, United Kingdom
b--Harvard University, United States
238
blank
2297588
nan
a--University of Cambridge, United Kingdom
b--Harvard University, United States
239
blank
2297655
nan
University of California, Berkeley, United States
240
blank
2297597
nan
Columbia University, United States
241
blank
2297651
nan
a--University of York, United Kingdom
b--University of East Anglia, United Kingdom
242
blank
2297653
nan
London School of Economics, United Kingdom
243
blank
2297638
nan
Princeton University, United States
244
blank
2297639
nan
a--Harvard University, United States
b--Unioersite des Sciences Sociales de Toulouse and EHESS, United States
245
blank
2297640
nan
a--Uniuersite d’Aix-Marseille III, United States
b--University of Bonn, Germany
246
blank
2297641
nan
Nuffield College, Oxford, United States
247
blank
2297637
nan
a--University College Dublin, Ireland
b--Australian National University, Australia
248
blank
2297647
nan
University of Pennsylvania, NBER, United States
249
blank
2297648
nan
a--Stanford University, United States
b--University of Helsinki, Yrjo Jahnsson Foundation, Finland
250
blank
2297649
nan
University of Amsterdam, Netherlands
251
blank
2297646
nan
a--University of Pennsylvania, United States
b--University of Bonn, Germany
252
blank
2297650
nan
Cowles Foundation for Research in Economics, Yale University, United States
253
blank
2297598
nan
Princeton University, United States
254
blank
2297652
nan
University of Tokyo, Japan
255
blank
2297636
nan
University of Texas, Austin, United States
256
blank
2297632
nan
Harvard University, United States
257
blank
2297634
nan
University of Pennsylvania, United States
258
blank
2297604
nan
Australian National University, Australia
259
blank
2297596
nan
Banco Central de Venezuela, United States
260
blank
2297612
nan
Federal Reserve Board, Washington, DC, United States
261
blank
2297611
nan
Nuffield College, Oxford, United States
262
blank
2297610
nan
Duke University, United States
263
blank
2297609
nan

(2613, 5)

In [46]:

RES_consolidated_master_scopus_merged_1981 = RES_consolidated_master_scopus_merged_1981[~RES_consolidated_master_scopus_merged_1981['0_author_affs_consolidated_0'].notna()]
RES_consolidated_master_scopus_merged_1981 = RES_consolidated_master_scopus_merged_1981[RES_consolidated_master_scopus_merged_1981['affiliations'].notna()]
RES_consolidated_master_scopus_merged_1981

,Article_ID,year_master,0_author_affs_consolidated_0,year,affiliations
2,2967408,1940,NaN,1940.0,"London, United Kingdom"
32,2967640,1941,NaN,1941.0,"Washington, DC, United States"
49,2967492,1942,NaN,1942.0,"London, United Kingdom"
52,2967520,1943,NaN,1943.0,"Stillwater, OK, United States"
104,2295923,1947,NaN,1947.0,"Cambridge, United Kingdom"
...,...,...,...,...,...
1988,2298076,1995,NaN,1995.0,a--DULBEA and EC ARE (Université Libre de Brux...
1989,2298112,1996,NaN,1996.0,"a--Institute d'Economie Industrielle, GREMAQ, ..."
2002,2297850,1996,NaN,1996.0,New York University
2005,2297890,1996,NaN,1996.0,"Université de Montréal, C.R.D.E."
2008,2297798,1996,NaN,1996.0,a--Korea University\nb--Inst. d'Analisi Econom...

In [51]:
# Read in the consolidated data

RES_scopus_consolidated = pd.read_excel('/Users/MattJohnson/Desktop/Affiliations/2_Extracting affilitations/3_consolidation/RES/Scopus/RES_scopus split consolidated 1940 2010.xlsx') 
RES_scopus_consolidated['year'] = RES_scopus_consolidated['year'].astype('int')

for i in range(len(RES_scopus_consolidated)):
    RES_scopus_consolidated.loc[i,['Article_ID']] = RES_scopus_consolidated.loc[i,['DOI']].to_string().rsplit('/',1)[-1]
#RES_scopus_consolidated['Article_ID'] = RES_scopus_consolidated['Article_ID'].astype('int')
RES_scopus_consolidated = RES_scopus_consolidated.reset_index(drop = True)
print(RES_scopus_consolidated.shape)
print(RES_scopus_consolidated.columns.values)
print(RES_scopus_consolidated.head())

(2832, 35)
['Unnamed: 0' 'authors' 'title' 'journal' 'volume' 'issue' 'year' 'pages'
 'DOI' 'affiliations' 'document type' '0_author' '0_author_affs_0'
 '0_author_affs_consolidated_0' '0_author_affs_1'
 '0_author_affs_consolidated_1' '0_author_affs_2'
 '0_author_affs_consolidated_2' '1_author' '1_author_affs_0'
 '1_author_affs_consolidated_0' '1_author_affs_1'
 '1_author_affs_consolidated_1' '2_author' '2_author_affs_0'
 '2_author_affs_consolidated_0' '2_author_affs_1'
 '2_author_affs_consolidated_1' '3_author' '3_author_affs_0'
 '3_author_affs_consolidated_0' '4_author' '4_author_affs_0'
 '4_author_affs_consolidated_0' 'Article_ID']
   Unnamed: 0                              authors  \
0           0                           Kaldor, N.
1           1                        Tinbergen, J.
2           2                          Kalecki, M.
3           3                            Lange, O.
4           4  Wensley, A.J., Sargant Florence, P.

                                               title  \
0  A symposium on the theory of the forward marke...
1                Econometric business cycle research
2  The supply curve of an industry under imperfec...
3  Complementarity and interrelations of shifts i...
4  Recent industrial concentration, especially in...

                      journal  volume  issue  year    pages              DOI  \
0  Review of Economic Studies     7.0    3.0  1940  196-201  10.2307/2967407
1  Review of Economic Studies     7.0    2.0  1940    73-90  10.2307/2967472
2  Review of Economic Studies     7.0    2.0  1940   91-112  10.2307/2967473
3  Review of Economic Studies     8.0    1.0  1940    58-63  10.2307/2967419
4  Review of Economic Studies     7.0    3.0  1940  139-158  10.2307/2967402

                 affiliations  ... 2_author_affs_consolidated_0  \
0      London, United Kingdom  ...                          NaN
1                         NaN  ...                          NaN
2    Cambridge, United States  ...                          NaN
3      Chicago, United States  ...                          NaN
4  Birmingham, United Kingdom  ...                          NaN

  2_author_affs_1 2_author_affs_consolidated_1 3_author 3_author_affs_0  \
0             NaN                          NaN      NaN             NaN
1             NaN                          NaN      NaN             NaN
2             NaN                          NaN      NaN             NaN
3             NaN                          NaN      NaN             NaN
4             NaN                          NaN      NaN             NaN

  3_author_affs_consolidated_0 4_author 4_author_affs_0  \
0                          NaN      NaN             NaN
1                          NaN      NaN             NaN
2                          NaN      NaN             NaN
3                          NaN      NaN             NaN
4                          NaN      NaN             NaN

  4_author_affs_consolidated_0 Article_ID
0                          NaN    2967407
1                          NaN    2967472
2                          NaN    2967473
3                          NaN    2967419
4                          NaN    2967402

[5 rows x 35 columns]

In [57]:
# Merging the masterfile onto the new melted file to get additional data
RES_consolidated_master_scopus_merged_1981 = RES_consolidated_master_scopus_merged_1981[['Article_ID']]
consolidated_master_merged = RES_consolidated_master_scopus_merged_1981.merge(RES_scopus_consolidated, how = 'left', on = 'Article_ID')
consolidated_master_merged = consolidated_master_merged.sort_values(by=['year'])
consolidated_master_merged = consolidated_master_merged.reset_index(drop = True)
print(consolidated_master_merged.shape)
consolidated_master_merged.to_excel('/Users/MattJohnson/Desktop/Affiliations/2_Extracting affilitations/3_consolidation/RES/Scopus/RES_scopus to add.xlsx')

(430, 35)