In [6]:
#RES
import pandas as pd
RES = pd.read_excel('/Users/MattJohnson/Library/CloudStorage/OneDrive-UniversityofCapeTown/Masters_thesis/Data checks/Consolidation/Finalized/RES_affiliations.xlsx', 'Affiliations')
print(RES.shape)
RES.head()

(2609, 48)

,Unnamed: 0,Article_ID,year_master,authors,content_type_master,Journal_Name,Authors_count,Authors_list,content_type,stable_url,...,5_author_affs,5_author_affs_consolidated,0_author_affs_consolidated_0_scopus,0_author_affs_consolidated_1_scopus,0_author_affs_consolidated_2_scopus,1_author_affs_consolidated_0_scopus,1_author_affs_consolidated_1_scopus,2_author_affs_consolidated_0_scopus,2_author_affs_consolidated_1_scopus,3_author_affs_consolidated_0_scopus
0,0,2967475,1940,S. S. Alexander,Article,RES,1.0,['S. S. Alexander'],Article,https://www.jstor.org/stable/2967475,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2967408,1940,J. C. R. Dow,Article,RES,1.0,['J. C. R. Dow'],Article,https://www.jstor.org/stable/2967408,...,NaN,NaN,London United Kingdom (City),NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2967408,1940,J. C. R. Dow,Article,RES,1.0,['J. C. R. Dow'],Article,https://www.jstor.org/stable/2967408,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2967405,1940,M. Bronfenbrenner,Article,RES,1.0,['M. Bronfenbrenner'],Article,https://www.jstor.org/stable/2967405,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2967406,1940,J. C. R. Dow,Article,RES,1.0,['J. C. R. Dow'],Article,https://www.jstor.org/stable/2967406,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#QJE
import pandas as pd
QJE = pd.read_excel('/Users/MattJohnson/Library/CloudStorage/OneDrive-UniversityofCapeTown/Masters_thesis/Data checks/Consolidation/Finalized/QJE_affiliations.xlsx', 'Affiliations')
print(QJE.shape)
QJE.head()

(2890, 62)

,Unnamed: 0.2,Unnamed: 0.1,Article_ID,year_master,authors,content_type_master,Unnamed: 0,Journal_Name,Authors_count,Authors_list,...,0_author_affs_consolidated_2_scopus,1_author_affs_consolidated_0_scopus,1_author_affs_consolidated_1_scopus,2_author_affs_consolidated_0_scopus,2_author_affs_consolidated_1_scopus,3_author_affs_consolidated_0_scopus,4_author_affs_consolidated_0_scopus,5_author_affs_consolidated_0_scopus,6_author_affs_consolidated_0_scopus,Scopus
0,0,0,1883343,1940,Wilfred Malenbaum,Article,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,1883336,1940,A. P. Lerner,Article,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scopus
2,2,3,1883335,1940,Fritz Machlup,Article,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scopus
3,3,4,1883334,1940,"Bennett S. White, Jr.",Article,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,5,1883333,1940,"Bennett S. White, Jr.",Article,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scopus

In [8]:
#JPE
import pandas as pd
JPE = pd.read_excel('/Users/MattJohnson/Library/CloudStorage/OneDrive-UniversityofCapeTown/Masters_thesis/Data checks/Consolidation/Finalized/JPE_affiliations.xlsx', 'Affiliations')
print(JPE.shape)
JPE.head()

(3823, 38)

,Unnamed: 0,Journal_Name,Authors_count,Authors_list,Article_ID,content_type,stable_url,Ref_type,ref_string,ref_string_clean1,...,3_author_affs,3_author_affs_consolidated,3_author_affs_consolidated_0,3_author_affs_consolidated_1,4_author_affs,4_author_affs_consolidated,4_author_affs_consolidated_0,5_author_affs,5_author_affs_consolidated,Unnamed: 37
0,0,JPE,1,['Gerhard Colm'],1825913,Article,https://www.jstor.org/stable/1825913,found,"COMMENTS ON W. I. KING: ""ARE WE SUFFERING\nFRO...",Comments On W. I. King Are We Suffering\nFrom ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,JPE,1,['Jules Backman'],1825487,Article,https://www.jstor.org/stable/1825487,found,FLEXIBILITY OF CHEESE PRICES\n\nJULES BACKMAN\...,Flexibility Of Cheese Prices\n\nJules Backman\...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,JPE,2,"['William Fellner', ' Howard S. Ellis']",1825486,Article,https://www.jstor.org/stable/1825486,found,HICKS AND THE TIME-PERIOD CONTROVERSY\n\nWILLI...,Hicks And The Time-Period Controversy\n\nWilli...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,JPE,1,['Harvey Pinney'],1825485,Article,https://www.jstor.org/stable/1825485,raw,['THE INSTITUTIONAL MAN\n\nHARVEY PINNEV\nNew ...,The Institutional Man\n\nHarvey Pinnev\nNew Yo...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,JPE,1,['George J. Stigler'],1825484,Article,https://www.jstor.org/stable/1825484,found,NOTES ON THE THEORY OF DUOPOLY\n\nGEORGE J. ST...,Notes On The Theory Of Duopoly\n\nGeorge J. St...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#AER
import pandas as pd
AER = pd.read_excel('/Users/MattJohnson/Library/CloudStorage/OneDrive-UniversityofCapeTown/Masters_thesis/Data checks/Consolidation/Finalized/AER_Merged.xlsx')
print(AER.shape)
AER.head()

(9340, 41)

,Unnamed: 0,Article_ID,Journal_Name,Authors_count,Authors_list,authors,content_type,stable_url,year_master,Ref_type,...,3_Auth_affs_2,3_Auth_affs_3,3_Auth_affs_4,4_Auth_affs_0,4_Auth_affs_1,4_Auth_affs_2,4_Auth_affs_3,5_Auth_affs_0,6_Auth_affs_0,7_Auth_affs_0
0,0,41038751,AER,1.0,['Enrique G. Mendoza'],Enrique G. Mendoza,Article,https://www.jstor.org/stable/41038751,2010.0,found,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,41038752,AER,3.0,"['Atif Mian', 'Amir Sufi', 'Francesco Trebbi']","Atif Mian, Amir Sufi and Francesco Trebbi",Article,https://www.jstor.org/stable/41038752,2010.0,found,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,41038753,AER,2.0,"['Marc-Andreas Muendler', 'Sascha O. Becker']",Marc-Andreas Muendler and Sascha O. Becker,Article,https://www.jstor.org/stable/41038753,2010.0,found,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,41038754,AER,2.0,"['Diego Comin', 'Bart Hobijn']",Diego Comin and Bart Hobijn,Article,https://www.jstor.org/stable/41038754,2010.0,found,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,41038755,AER,2.0,"['Yann Algan', 'Pierre Cahuc']",Yann Algan and Pierre Cahuc,Article,https://www.jstor.org/stable/41038755,2010.0,found,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
#Mturk batch 1
import pandas as pd
Mturk1 = pd.read_excel('/Users/MattJohnson/Library/CloudStorage/OneDrive-UniversityofCapeTown/Masters_thesis/Data checks/Consolidation/Finalized/Mturk1.xlsx')
print(Mturk1.shape)
Mturk1.head()

(1026, 42)

,HITId,HITTypeId,Title,Description,Keywords,Reward,CreationTime,MaxAssignments,RequesterAnnotation,AssignmentDurationInSeconds,...,Answer.child_0_2,Answer.child_0_3,Answer.child_1_1,Answer.child_1_2,Answer.child_1_3,Answer.child_2_1,Answer.child_2_2,Answer.child_3_1,Approve,Reject
0,3CKVGCS3QN0FDOS0E80Z23RIEO60SQ,3ZNZSREO6KT41IS864PURQ3NZX8XZ8,Recording affiliations of authors of academic ...,Scroll through a pdf of an academic article an...,"Data entry, typing",0.1,Thu Sep 15 08:02:04 PDT 2022,1,BatchId:4838893;OriginalHitTemplateId:928390828;,1800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3W9XHF7WHRQI5ECJ71F7VS2DU5PTKD,3ZNZSREO6KT41IS864PURQ3NZX8XZ8,Recording affiliations of authors of academic ...,Scroll through a pdf of an academic article an...,"Data entry, typing",0.1,Thu Sep 15 08:02:18 PDT 2022,1,BatchId:4838893;OriginalHitTemplateId:928390828;,1800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,33EEIIWHLE2JT9E3P1ZJSW27QWXQVI,3ZNZSREO6KT41IS864PURQ3NZX8XZ8,Recording affiliations of authors of academic ...,Scroll through a pdf of an academic article an...,"Data entry, typing",0.1,Thu Sep 15 08:02:17 PDT 2022,1,BatchId:4838893;OriginalHitTemplateId:928390828;,1800,...,NaN,NaN,Iowa State University,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3H781YYV70DFJEK9BF44XXP8A8TTET,3ZNZSREO6KT41IS864PURQ3NZX8XZ8,Recording affiliations of authors of academic ...,Scroll through a pdf of an academic article an...,"Data entry, typing",0.1,Thu Sep 15 08:02:04 PDT 2022,1,BatchId:4838893;OriginalHitTemplateId:928390828;,1800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3YGE63DIOFS8K599YDA0ZSU3K11W00,3ZNZSREO6KT41IS864PURQ3NZX8XZ8,Recording affiliations of authors of academic ...,Scroll through a pdf of an academic article an...,"Data entry, typing",0.1,Thu Sep 15 08:02:18 PDT 2022,1,BatchId:4838893;OriginalHitTemplateId:928390828;,1800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
RES.rename(columns={"0_author_affs_consolidated_0": "0_Auth_affs_0", "0_author_affs_consolidated_1": "0_Auth_affs_1",
                    "0_author_affs_consolidated_2": "0_Auth_affs_2", "0_author_affs_consolidated_3": "0_Auth_affs_3",
                    "1_author_affs_consolidated_0": "1_Auth_affs_0", "1_author_affs_consolidated_1": "1_Auth_affs_1",
                    "2_author_affs_consolidated_0": "2_Auth_affs_0", "2_author_affs_consolidated_1": "2_Auth_affs_1",
                    "2_author_affs_consolidated_2": "2_Auth_affs_2",
                    "3_author_affs_consolidated_0": "3_Auth_affs_0", "3_author_affs_consolidated_1": "3_Auth_affs_1",
                    "4_author_affs_consolidated_0": "4_Auth_affs_0",
                    "5_author_affs_consolidated": "5_Auth_affs_0",}, inplace= True)

RES['0_Auth_affs_4'] = ""
RES['1_Auth_affs_2'] = ""
RES['1_Auth_affs_3'] = ""
RES['1_Auth_affs_4'] = ""
RES['2_Auth_affs_3'] = ""
RES['2_Auth_affs_4'] = ""
RES['3_Auth_affs_2'] = ""
RES['3_Auth_affs_3'] = ""
RES['3_Auth_affs_4'] = ""

RES['4_Auth_affs_1'] = ""
RES['4_Auth_affs_2'] = ""
RES['4_Auth_affs_3'] = ""
RES['6_Auth_affs_0'] = ""
RES['7_Auth_affs_0'] = ""

print(RES.shape)

RES = RES[['Journal_Name' ,'Authors_count', 'Authors_list', 'authors', 'Article_ID', 'content_type',
'stable_url', 'year_master', 'Ref_type' ,
'ref_string', 'ref_string_clean1', 'Screened', 'Manual',
'0_Auth_affs_0', '0_Auth_affs_1', '0_Auth_affs_2', '0_Auth_affs_3', '0_Auth_affs_4', 
'1_Auth_affs_0' , '1_Auth_affs_1', '1_Auth_affs_2', '1_Auth_affs_3', '1_Auth_affs_4',
'2_Auth_affs_0', '2_Auth_affs_1', '2_Auth_affs_2', '2_Auth_affs_3', '2_Auth_affs_4',
'3_Auth_affs_0', '3_Auth_affs_1', '3_Auth_affs_2', '3_Auth_affs_3', '3_Auth_affs_4',
'4_Auth_affs_0', '4_Auth_affs_1', '4_Auth_affs_2' , '4_Auth_affs_3',
'5_Auth_affs_0',
'6_Auth_affs_0','7_Auth_affs_0']]

print(RES.shape)

#QJE
QJE.rename(columns={"ref_string_found": "ref_string", "ref_string_found_clean": "ref_string_clean1",
                    "0_author_affs_consolidated_0": "0_Auth_affs_0", "0_author_affs_consolidated_1": "0_Auth_affs_1",
                    "0_author_affs_consolidated_2": "0_Auth_affs_2", "0_author_affs_consolidated_3": "0_Auth_affs_3",
                    "0_author_affs_consolidated_4": "0_Auth_affs_4",
                    "1_author_affs_consolidated_0": "1_Auth_affs_0", "1_author_affs_consolidated_1": "1_Auth_affs_1",
                    "1_author_affs_consolidated_2": "1_Auth_affs_2", "1_author_affs_consolidated_3": "1_Auth_affs_3",
                    "2_author_affs_consolidated_0": "2_Auth_affs_0", "2_author_affs_consolidated_1": "2_Auth_affs_1",
                    "2_author_affs_consolidated_2": "2_Auth_affs_2", "2_author_affs_consolidated_3": "2_Auth_affs_3",
                    "3_author_affs_consolidated_0": "3_Auth_affs_0", "3_author_affs_consolidated_1": "3_Auth_affs_1",
                    "3_author_affs_consolidated_2": "3_Auth_affs_2",
                    "4_author_affs_consolidated_0": "4_Auth_affs_0",
                    "5_author_affs_consolidated": "5_Auth_affs_0",}, inplace= True)


QJE['1_Auth_affs_4'] = ""
QJE['2_Auth_affs_4'] = ""

QJE['3_Auth_affs_3'] = ""
QJE['3_Auth_affs_4'] = ""

QJE['4_Auth_affs_1'] = ""
QJE['4_Auth_affs_2'] = ""
QJE['4_Auth_affs_3'] = ""
QJE['6_Auth_affs_0'] = ""
QJE['7_Auth_affs_0'] = ""

print(QJE.shape)

QJE = QJE[['Journal_Name' ,'Authors_count', 'Authors_list', 'authors', 'Article_ID', 'content_type',
'stable_url', 'year_master', 'Ref_type' ,
'ref_string', 'ref_string_clean1', 'Screened', 'Manual',
'0_Auth_affs_0', '0_Auth_affs_1', '0_Auth_affs_2', '0_Auth_affs_3', '0_Auth_affs_4', 
'1_Auth_affs_0' , '1_Auth_affs_1', '1_Auth_affs_2', '1_Auth_affs_3', '1_Auth_affs_4',
'2_Auth_affs_0', '2_Auth_affs_1', '2_Auth_affs_2', '2_Auth_affs_3', '2_Auth_affs_4',
'3_Auth_affs_0', '3_Auth_affs_1', '3_Auth_affs_2', '3_Auth_affs_3', '3_Auth_affs_4',
'4_Auth_affs_0', '4_Auth_affs_1', '4_Auth_affs_2' , '4_Auth_affs_3',
'5_Auth_affs_0',
'6_Auth_affs_0','7_Auth_affs_0']]

print(QJE.shape)

#JPE
JPE.rename(columns={"year": "year_master","0_author_affs_consolidated_0": "0_Auth_affs_0", "0_author_affs_consolidated_1": "0_Auth_affs_1",
                    "0_author_affs_consolidated_2": "0_Auth_affs_2", 
                    "1_author_affs_consolidated_0": "1_Auth_affs_0", "1_author_affs_consolidated_1": "1_Auth_affs_1",
                    "1_author_affs_consolidated_2": "1_Auth_affs_2",
                    "2_author_affs_consolidated_0": "2_Auth_affs_0", "2_author_affs_consolidated_1": "2_Auth_affs_1",
                    "2_author_affs_consolidated_2": "2_Auth_affs_2",
                    "3_author_affs_consolidated_0": "3_Auth_affs_0", "3_author_affs_consolidated_1": "3_Auth_affs_1",
                    "4_author_affs_consolidated_0": "4_Auth_affs_0",
                    "5_author_affs_consolidated": "5_Auth_affs_0",}, inplace= True)

JPE['authors'] = ""

JPE['0_Auth_affs_3'] = ""
JPE['0_Auth_affs_4'] = ""

JPE['1_Auth_affs_3'] = ""
JPE['1_Auth_affs_4'] = ""
JPE['2_Auth_affs_3'] = ""
JPE['2_Auth_affs_4'] = ""
JPE['3_Auth_affs_2'] = ""
JPE['3_Auth_affs_3'] = ""
JPE['3_Auth_affs_4'] = ""

JPE['4_Auth_affs_1'] = ""
JPE['4_Auth_affs_2'] = ""
JPE['4_Auth_affs_3'] = ""
JPE['6_Auth_affs_0'] = ""
JPE['7_Auth_affs_0'] = ""

print(JPE.shape)

JPE = JPE[['Journal_Name' ,'Authors_count', 'Authors_list', 'authors', 'Article_ID', 'content_type',
'stable_url', 'year_master', 'Ref_type' ,
'ref_string', 'ref_string_clean1', 'Screened', 'Manual',
'0_Auth_affs_0', '0_Auth_affs_1', '0_Auth_affs_2', '0_Auth_affs_3', '0_Auth_affs_4', 
'1_Auth_affs_0' , '1_Auth_affs_1', '1_Auth_affs_2', '1_Auth_affs_3', '1_Auth_affs_4',
'2_Auth_affs_0', '2_Auth_affs_1', '2_Auth_affs_2', '2_Auth_affs_3', '2_Auth_affs_4',
'3_Auth_affs_0', '3_Auth_affs_1', '3_Auth_affs_2', '3_Auth_affs_3', '3_Auth_affs_4',
'4_Auth_affs_0', '4_Auth_affs_1', '4_Auth_affs_2' , '4_Auth_affs_3',
'5_Auth_affs_0',
'6_Auth_affs_0','7_Auth_affs_0']]

#AER
AER = AER[['Journal_Name' ,'Authors_count', 'Authors_list', 'authors', 'Article_ID', 'content_type',
'stable_url', 'year_master', 'Ref_type' ,
'ref_string', 'ref_string_clean1', 'Screened', 'Manual',
'0_Auth_affs_0', '0_Auth_affs_1', '0_Auth_affs_2', '0_Auth_affs_3', '0_Auth_affs_4', 
'1_Auth_affs_0' , '1_Auth_affs_1', '1_Auth_affs_2', '1_Auth_affs_3', '1_Auth_affs_4',
'2_Auth_affs_0', '2_Auth_affs_1', '2_Auth_affs_2', '2_Auth_affs_3', '2_Auth_affs_4',
'3_Auth_affs_0', '3_Auth_affs_1', '3_Auth_affs_2', '3_Auth_affs_3', '3_Auth_affs_4',
'4_Auth_affs_0', '4_Auth_affs_1', '4_Auth_affs_2' , '4_Auth_affs_3',
'5_Auth_affs_0',
'6_Auth_affs_0','7_Auth_affs_0']]

print(AER.shape)

(2609, 40)
(2609, 40)
(2890, 40)
(2890, 40)
(3823, 53)
(9340, 40)

In [16]:
Merged_all = pd.concat([RES, QJE, JPE, AER])

In [ ]:
# Merging the masterfile onto the new melted file to get additional data
#AER_Merged = AER_master_condenced.merge(AER_Merge_base, how = 'left', on = 'Article_ID')

In [17]:
# Excel output to get an overview of the data
Merged_all.head
Merged_all.to_excel('/Users/MattJohnson/Desktop/Affiliations/2_Extracting affilitations/3_consolidation/Merged_all.xlsx')